# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Li Yong
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://print.199681.xyz

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Li Yong
  description:
    - Hello!
    - This tiny website
    - 热爱生活，知足常乐
  cv: assets/cv.pdf
  address:
    - Anywhere, Anytime
    - hubei province
    - People's Republic of China
  contact:
    word: 昨天是段历史，明天是个谜团，而今天是天赐的礼物，要像珍惜礼物那样珍惜今天
    translation: Yesterday is history, tomorrow is a mystery, and today is a gift from God. Cherish today like a gift.
    email: nicedaytoooyou@gmail.com
    office: https://www.199681.xyz
    way: https://kee.so/liyong
  profiles:
    facebook: https://www.facebook.com/100087409027814
    twitter: https://twitter.com/NiceDayTooYou
    instagram: https://www.instagram.com/serendipityniceday
    youtube: https://youtube.com/@serendipityniceday
    official: https://www.199681.xyz
    github: https://github.com/NiceDayTooYou

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
